#Aplicatgion configuration
server:
  port: 8091

# http://localhost:8091/h2-console
# Enabled H2 console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      platform: h2
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

#spring.application.name=service-product
#spring.datasource.url=jdbc:h2:~/products
#spring.datasource.driverClassName=org.h2.Driver
# Username and password (optional, defaults are 'sa' and '')
#spring.datasource.username=sa
#spring.datasource.password=