server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jobBurroGuinda/microservice1.git
          search-paths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSW}

  security:
    user:
      name: root
      password: s3cr3t
